blank_issues_enabled: false
contact_links:
  - name: "ğŸ’¬ Discussions / DiscussÃµes"
    url: https://github.com/Erick-Bryan-Cubas/green-deck/discussions
    about: |
      ğŸ‡ºğŸ‡¸ Ask questions and discuss ideas
      ğŸ‡§ğŸ‡· FaÃ§a perguntas e discuta ideias
  - name: "ğŸ“– Documentation / DocumentaÃ§Ã£o"
    url: https://github.com/Erick-Bryan-Cubas/green-deck#readme
    about: |
      ğŸ‡ºğŸ‡¸ Check out the documentation
      ğŸ‡§ğŸ‡· Confira a documentaÃ§Ã£o
